from pathlib import Path
import re

narrations = [
    ("SCENE 1: CNN Failure", "Slot Attention ban đầu dùng CNN nhỏ (ví dụ 4 layer) trích xuất feature. Phương pháp này rất tốt trên dataset synthetic như CLEVR, nhưng thất bại hoàn toàn trên dữ liệu thực tế. Mô hình không thể phân tách object và tạo ra các mask vô nghĩa. Nguyên nhân là pixel reconstruction tạo signal quá yếu. Khi bị ép tái tạo toàn bộ ảnh, mô hình tập trung vào low-level features như màu sắc và texture, thay vì cấu trúc vật thể. Các thí nghiệm của DINOSAUR chứng minh điều này: dùng ViT-B/16 từ scratch, frozen hay finetuned đều thất bại, cho thấy image reconstruction không cung cấp đủ signal cho semantic grouping."),
    ("SCENE 2: Feature Reconstruction", "Nếu pixel reconstruction quá yếu, signal nào đủ mạnh? Câu trả lời là Self-Supervised Learning (SSL). Các thuật toán như DINO, MoCo-v3 học representation mạnh mẽ hoàn toàn unsupervised. Ý tưởng của DINOSAUR: thay vì tái tạo ảnh gốc, hãy tái tạo feature maps từ mô hình DINO pre-trained. Điều này tạo ra training signal giàu semantic hơn nhiều. Có thể hiểu cơ chế này như Student-Teacher Knowledge Distillation. Teacher (DINO ViT) cung cấp feature phong phú, Student (Slot Attention) nén thông tin đó vào K slots. Quá trình này ép slot học biểu diễn có cấu trúc. Đây là bước ngoặt cho object-centric learning."),
    ("SCENE 3: ViT Architecture", "Vision Transformer (ViT) tạo bước ngoặt bằng cách chia ảnh thành các patch (16x16), biến thành token và xử lý qua Transformer. ViT vượt trội CNN cho object-centric learning ở hai điểm. Thứ nhất, global self-attention nắm bắt quan hệ toàn ảnh. Thứ hai, layer sâu của ViT tự nhiên phân tách vùng semantic tương ứng object ('object property'). Đặc biệt, DINO-trained ViT tạo attention map gần giống segmentation mask. Dù encoder ResNet34 train from scratch có hiệu năng tương đương, ViT vẫn được ưu tiên vì hội tụ nhanh và hiệu quả hơn."),
    ("SCENE 4: DINOSAUR Model", "DINOSAUR là mô hình đầu tiên đưa object-centric learning lên dữ liệu thực tế hoàn toàn unsupervised. Kiến trúc gồm ba phần. Một: Encoder dùng DINO ViT frozen để trích patch features, dùng làm target reconstruction. Hai: Slot Attention, nơi K slot cạnh tranh để phân nhóm encoded features thành object slots. Ba: Decoder, dùng MLP hoặc Transformer để tái tạo features. Loss function là MSE giữa reconstructed features và target features trong semantic space. DINOSAUR out-perform mọi model trên CLEVR và là mô hình unsupervised đầu tiên scale được lên PASCAL VOC và COCO."),
    ("SCENE 5: SSL Comparison", "Thuật toán SSL nào phù hợp nhất? Thí nghiệm của DINOSAUR trên DINO, MoCo-v3, MSN và MAE cho thấy tất cả đều tốt, chứng tỏ SSL pre-training tạo general bias hữu ích. DINO được chọn vì hiệu năng cao và ViT có 'object property' tự nhiên. MAE học tốt nhưng thiên về low-level features hơn. Thí nghiệm cũng chỉ ra ViT cho kết quả tốt hơn ResNet ở cả vai trò encoder và target provider, củng cố vị thế của ViT như một backbone mạnh mẽ cho object-centric representation learning."),
    ("SCENE 6: Encoder Upgrade Challenge", "Nâng cấp encoder lên ViT không chỉ là thay thế CNN. Vấn đề là: encoder càng lớn, không gian feature ở đầu ra Slot Attention càng xa so với RGB gốc. Khi đó, ta không thể dùng CNN decoder nhỏ để tái tạo ảnh gốc nữa. Giải pháp của DINOSAUR là không reconstruct pixel, mà reconstruct trong hidden feature space của teacher model. Điều này giữ nguyên sức mạnh của encoder mà không cần decoder phức tạp. Pipeline trở thành: Image -> Encoder -> Slot Attention -> Decoder -> Reconstructed Features, tối ưu hóa bằng MSE loss."),
    ("SCENE 7: Optical Flow & Depth", "Trước DINOSAUR, các nghiên cứu cố gắng reconstruct tín hiệu khác ít nhiễu hơn RGB. SAVi (Slot Attention for Video) reconstruct optical flow từ video. Optical flow mô tả chuyển động pixel, cung cấp tín hiệu mạnh vì các phần của cùng object thường chuyển động giống nhau. SAVi++ tiến xa hơn bằng cách reconstruct depth từ LiDAR. Depth mang thông tin hình học, ổn định trước ánh sáng và texture. Tuy nhiên, cả hai đều đòi hỏi dữ liệu đặc thù (video hoặc LiDAR), hạn chế tính ứng dụng thực tế."),
    ("SCENE 8: Dynamic Slots (AdaSlot)", "Một vấn đề tồn đọng: số lượng slot K phải được định trước. Nếu K sai lệch so với số object thực tế, model sẽ thiếu sót hoặc phân mảnh object. AdaSlot giải quyết bằng dynamic slot selection. Nó bắt đầu với nhiều slot, dùng Gumbel Softmax để chọn số slot phù hợp. AdaSlot dùng thêm regularization loss để kiểm soát số lượng slot trung bình. Kết quả: AdaSlot vượt trội DINOSAUR trên COCO về mọi mặt, tự động thích ứng với số lượng object đa dạng trong ảnh."),
    ("SCENE 9: Temporal Similarity (VideoSaur)", "VideoSaur tiếp cận khác biệt: thay vì reconstruct features, nó train slots để dự đoán temporal feature similarity. Slot Attention nhóm features từ ViT thành slots, sau đó model dự đoán ma trận similarity giữa các frame, so sánh với ground-truth cosine distance. Phương pháp này không cần reconstruct trực tiếp, giảm độ phức tạp của decoder mà vẫn học được biểu diễn object qua thời gian rất hiệu quả."),
    ("SCENE 10: Part 6 Summary", "Tóm lại Phần 6: Pixel reconstruction quá yếu cho dữ liệu thực tế vì tập trung vào màu sắc. Self-supervised feature reconstruction (như DINO ViT) tạo signal đủ mạnh cho object grouping. Các giải pháp như reconstruct optical flow, depth, dynamic slots (AdaSlot) và temporal similarity (VideoSaur) đang không ngừng mở rộng giới hạn của object-centric learning."),
    ("SCENE 11: Slot-Decoding Dilemma", "Phần 7: Nâng cấp Decoder. Object-centric learning gặp Slot-Decoding Dilemma: Decoder yếu (như Spatial Broadcast) ép slot học object disentanglement tốt nhưng ảnh mờ, thiếu chi tiết. Decoder mạnh (như CNN) tạo ảnh sắc nét nhưng tự học hết thông tin, khiến slot mất tính object-centric. Không có sự thỏa hiệp hoàn hảo, đòi hỏi cách tiếp cận mới hoàn toàn để giải quyết nghịch lý này."),
    ("SCENE 12: Pixel Independence", "Vấn đề thứ hai là Pixel Independence. Pixel-mixture decoder truyền thống sinh từng pixel độc lập. Khi ghép slot từ các ảnh khác, nó tạo ra Frankenstein images thiếu tính nhất quán toàn cục. Để dùng slot như concept modules tái sử dụng được, ta cần autoregressive generation (sinh pixel phụ thuộc pixel trước đó) để đảm bảo global semantic consistency, dù mục tiêu là hoàn toàn unsupervised."),
    ("SCENE 13: 3D Bias & Decoupling", "Có hai hướng giải quyết Slot-Decoding Dilemma. Hướng 1: 3D Inductive Bias. Cung cấp thông tin hình học 3D (camera pose) để giúp decoder tạo ảnh tốt mà không cần quá mạnh (vd: ObSuRF, OSRT). Hướng 2: Decoupling Decoding. Tách biệt decoding thành nhiều giai đoạn, decode qua ngôn ngữ trung gian (VQ tokens, latent space) thay vì trực tiếp sang pixels (vd: SLATE, LSD, DORSAL). Cả hai đều giảm gánh nặng tái tạo ảnh trực tiếp."),
    ("SCENE 14: MLP vs Transformer", "DINOSAUR so sánh hai loại decoder: MLP và Transformer. MLP Decoder xử lý từng slot độc lập rồi dùng weighted sum. Nó tính toán cực kỳ hiệu quả, parallelize tốt và tách instance riêng biệt mạnh hơn. Transformer Decoder sinh feature autoregressive, duy trì global consistency, nhưng dễ phân mảnh object. Khuyến nghị: dùng MLP làm first choice vì tính ổn định và tách instance tốt."),
    ("SCENE 15: SLATE", "SLATE giải quyết cả hai vấn đề bằng ngôn ngữ trung gian: discrete tokens từ DVAE. Ảnh được biến thành tokens, Slot Attention hoạt động trên token space, và Transformer decoder reconstruct tokens autoregressive. Đột phá của SLATE là Visual Concept Library: gom nhóm slots thành các khái niệm. Ta có thể chọn slots từ thư viện này để tạo scene hoàn toàn mới (zero-shot generation) với full semantic consistency."),
    ("SCENE 16: Latent Slot Diffusion", "Latent Slot Diffusion (LSD) kết hợp Latent Diffusion Models và slot representations. LSD nén ảnh thành latent z0 qua Auto-Encoder, sau đó diffusion denoising được condition trên object slots qua cross-attention. LSD cho phép thao tác composition mạnh mẽ: xóa object, chèn object mới, đổi background, và lần đầu tiên cho phép face editing trên ảnh thực tế mà không phá vỡ tính nhất quán."),
    ("SCENE 17: DORSAL", "DORSAL nâng diffusion-based decoder lên 3D scene rendering. Nó kết hợp OSRT và video diffusion: OSRT encode context views thành Object Slots, dùng làm conditioning cho Multiview U-Net diffusion. DORSAL tạo ra multiple views nhất quán không gian. Dù PSNR có thể thấp hơn OSRT, DORSAL cho FID score vượt trội, sinh ảnh sắc nét và realistic hơn nhiều trên dữ liệu thực tế như Street View."),
    ("SCENE 18: ObSuRF", "ObSuRF thay CNN decoder bằng Neural Radiance Field (NeRF) 3D. Mỗi slot được map sang một NeRF độc lập, sinh volume density và radiance. Nhờ 3D inductive bias, ObSuRF hiểu cấu trúc không gian và render novel views xuất sắc. Hạn chế là yêu cầu dữ liệu multi-view và tính toán cực nặng do volumetric rendering, chủ yếu hoạt động trên dữ liệu tổng hợp (CLEVR-3D)."),
    ("SCENE 19: OSRT", "OSRT (Object Scene Representation Transformer) cải tiến 3D bằng Slot Mixer Decoder: trộn slots trước khi map sang ảnh thay vì render độc lập. OSRT dùng light-field rendering, giảm chi phí tính toán 100 lần so với NeRF. Nhờ đó, nó scale được lên dataset thực tế như Street View. OSRT cũng đóng vai trò backbone tạo object slots cho mô hình diffusion DORSAL."),
    ("SCENE 20: SysBinder", "Neural Systematic Binder (SysBinder) giải quyết việc disentangle các thuộc tính của object. SysBinder chia một slot thành nhiều block mã hóa riêng biệt (ví dụ: hình dạng, màu sắc, vị trí). Nhờ đó, ta có thể chỉnh sửa từng thuộc tính độc lập thay vì phải thay toàn bộ object, mang lại khả năng systematic generalization mạnh mẽ."),
    ("SCENE 21: MoToK", "MoToK đề xuất reconstruct nhiều modalities cùng lúc (RGB, Optical Flow, Depth, Token) bằng cách dùng pseudo segmentation masks từ chuyển động. Slot Decoder đa dạng (CNN, Transformer) cho phép reconstruct đồng thời. Việc này ép slot học representation phong phú và sâu sắc hơn từ nhiều nguồn tín hiệu, không chỉ dựa vào ảnh tĩnh RGB."),
    ("SCENE 22: CoSA", "CoSA cải tiến SLATE bằng Grounded Slot Dictionary (GSD). Thay vì dùng K-means gom cụm không rõ ý nghĩa, CoSA bind các slot element vào loại object cụ thể (như mắt, má, trán trong khuôn mặt). Điều này cung cấp ground truth semantic, giúp compose image chính xác và có kiểm soát hơn nhiều trong các ứng dụng sinh ảnh có cấu trúc."),
    ("SCENE 23: ISA", "Invariant Slot Attention (ISA) giải quyết vấn đề object đối xứng không gian (spatial symmetry) - vốn làm Slot Attention phân mảnh object. ISA control slot position, scale, và orientation bằng reference frames. Nhờ đó, mô hình nhận diện trọn vẹn object dù đối xứng, và cho phép thao tác di chuyển, đổi kích thước mà không phá hủy cấu trúc."),
    ("SCENE 24: DiffFAE", "DiffFAE ứng dụng slot-based decoder vào facial editing. Nó dùng Slot Attention trích semantic tokens từ 4 vùng khuôn mặt, rồi finetune Latent Diffusion Model (qua Cross-Attention, AdaIN) để đưa slot features vào quá trình sinh ảnh. Kết quả: chỉnh sửa được biểu cảm, ánh sáng mà vẫn giữ identity, vượt trội hơn các feature tổng quát từ CLIP hay MAE."),
    ("SCENE 25: PaLM-E", "PaLM-E kết hợp object-centric representation với Large Language Model. Nó đưa object slots từ OSRT làm input cho LLM. PaLM-E thể hiện xuất sắc trên các task embodied AI (Mobile Manipulation, Task Planning). Object-centric representation không chỉ dừng ở segmentation mà còn làm cầu nối giữa nhận thức hình ảnh và suy luận ngôn ngữ cho robot."),
    ("SCENE 26: Three Paradigms", "Có 3 paradigms thao tác với slots: 1. Substituting (Thay thế): Thay một slot bằng slot khác (như SLATE). 2. Manipulating (Chỉnh sửa): Thay đổi thuộc tính của slot (như đổi màu trong SysBinder, đổi biểu cảm trong DiffFAE). 3. Moving (Di chuyển): Dịch chuyển vị trí slot trong scene (như ISA). Đây là khung tư duy rõ ràng về ứng dụng object-centric."),
    ("SCENE 27: Part 7 Summary", "Tóm lại Phần 7: Xu hướng nâng cấp Decoder đi từ MLP đơn giản đến Generative Model mạnh mẽ (Transformer, Diffusion). Thay vì ép decoder yếu để giữ slot, ta dùng decoder mạnh kèm thiết kế khéo léo (3D Bias, Decoupling) để tái tạo ảnh đẹp mà slot vẫn object-centric. Ứng dụng đang mở rộng mạnh mẽ sang Generative AI và Robotics.")
]

content = ""
for i, (title, text) in enumerate(narrations, 1):
    content += f"### {title}\\n"
    content += f"**Thời gian video: TBD**\\n\\n"
    content += f'"{text}"\\n\\n---\\n\\n'

Path("merged_script_content.txt").write_text(content, encoding="utf-8")
print("merged_script_content.txt has been updated and shortened.")

# Let's also update build_pipeline.py so it doesn't overwrite scene_part6_7.py anymore!
bp_path = Path("build_pipeline.py")
bp_content = bp_path.read_text(encoding="utf-8")
bp_content = bp_content.replace(
    'Path("scene_part6_7.py").write_text(scene_code, encoding="utf-8")',
    '# Path("scene_part6_7.py").write_text(scene_code, encoding="utf-8") # DISABLED to protect manual edits'
)
bp_path.write_text(bp_content, encoding="utf-8")
print("Disabled overwrite of scene_part6_7.py in build_pipeline.py")

